package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-9-argm_o/openjdk-9-9~b114/src/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Thursday, April 14, 2016 7:54:06 PM UTC
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
     * Constant, defined in the Messaging spec, to define how far the 
     * request shall progress before control is returned to the client.
     */
  public static final short value = (short)(1);
}
