package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-9-argm_o/openjdk-9-9~b114/src/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, April 14, 2016 7:54:05 PM UTC
*/

public interface TransactionService
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CosTSInteroperation.PropogationContext</code> defined in 
       * <i>CORBAservices: Common Object Services Specifications.</i>
       */
  public static final int value = (int)(0L);
}
