package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/Interceptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-9-argm_o/openjdk-9-9~b114/src/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, April 14, 2016 7:54:06 PM UTC
*/


/**
   * All Portable Interceptors implement Interceptor.
   */
public interface Interceptor extends InterceptorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interceptor
