package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/UNKNOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, February 13, 2017 3:20:12 PM UTC
*/

public interface UNKNOWN
{

  /**
     * XXX
     */
  public static final short value = (short)(5);
}
