package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-9-argm_o/openjdk-9-9~b114/src/corba/src/java.corba/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, April 14, 2016 7:54:03 PM UTC
*/

public interface IIOP_CLEAR_TEXT
{

  // to avoid a compilation dependency.
  public static final String value = "IIOP_CLEAR_TEXT";
}
