package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/ServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /build/openjdk-9-argm_o/openjdk-9-9~b114/src/corba/src/java.corba/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, April 14, 2016 7:54:03 PM UTC
*/

public interface ServerManagerOperations  extends com.sun.corba.se.spi.activation.ActivatorOperations, com.sun.corba.se.spi.activation.LocatorOperations
{
} // interface ServerManagerOperations
