/*
 * Copyright (c) 2012, 2016, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright (C) 1991-2015 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in 
 * http://www.unicode.org/copyright.html.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of the Unicode data files and any associated documentation
 * (the "Data Files") or Unicode software and any associated documentation
 * (the "Software") to deal in the Data Files or Software
 * without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, and/or sell copies of
 * the Data Files or Software, and to permit persons to whom the Data Files
 * or Software are furnished to do so, provided that
 * (a) this copyright and permission notice appear with all copies 
 * of the Data Files or Software,
 * (b) this copyright and permission notice appear in associated 
 * documentation, and
 * (c) there is clear notice in each modified Data File or in the Software
 * as well as in the documentation associated with the Data File(s) or
 * Software that the data or software has been modified.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT OF THIRD PARTY RIGHTS.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
 * NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
 * DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THE DATA FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder
 * shall not be used in advertising or otherwise to promote the sale,
 * use or other dealings in these Data Files or Software without prior
 * written authorization of the copyright holder.
 */

package sun.util.resources.cldr.ext;

import sun.util.resources.OpenListResourceBundle;

public class CurrencyNames_is extends OpenListResourceBundle {
    @Override
    protected final Object[][] getContents() {
        final Object[][] data = new Object[][] {
            { "AED", "AED" },
            { "AFN", "AFN" },
            { "ALL", "ALL" },
            { "AMD", "AMD" },
            { "ANG", "ANG" },
            { "AOA", "AOA" },
            { "ARS", "ARS" },
            { "AUD", "AUD" },
            { "AWG", "AWG" },
            { "AZN", "AZN" },
            { "BAM", "BAM" },
            { "BBD", "BBD" },
            { "BDT", "BDT" },
            { "BGN", "BGN" },
            { "BHD", "BHD" },
            { "BIF", "BIF" },
            { "BMD", "BMD" },
            { "BND", "BND" },
            { "BOB", "BOB" },
            { "BRL", "BRL" },
            { "BSD", "BSD" },
            { "BTN", "BTN" },
            { "BWP", "BWP" },
            { "BYR", "BYR" },
            { "BZD", "BZD" },
            { "CAD", "CAD" },
            { "CDF", "CDF" },
            { "CHF", "CHF" },
            { "CLP", "CLP" },
            { "COP", "COP" },
            { "CRC", "CRC" },
            { "CUC", "CUC" },
            { "CUP", "CUP" },
            { "CVE", "CVE" },
            { "CZK", "CZK" },
            { "DJF", "DJF" },
            { "DKK", "DKK" },
            { "DOP", "DOP" },
            { "DZD", "DZD" },
            { "EGP", "EGP" },
            { "ERN", "ERN" },
            { "ETB", "ETB" },
            { "EUR", "EUR" },
            { "FJD", "FJD" },
            { "FKP", "FKP" },
            { "GBP", "GBP" },
            { "GEL", "GEL" },
            { "GHS", "GHS" },
            { "GIP", "GIP" },
            { "GMD", "GMD" },
            { "GNF", "GNF" },
            { "GTQ", "GTQ" },
            { "GYD", "GYD" },
            { "HNL", "HNL" },
            { "HRK", "HRK" },
            { "HTG", "HTG" },
            { "HUF", "HUF" },
            { "IDR", "IDR" },
            { "INR", "INR" },
            { "IQD", "IQD" },
            { "IRR", "IRR" },
            { "ISK", "ISK" },
            { "JMD", "JMD" },
            { "JOD", "JOD" },
            { "KES", "KES" },
            { "KGS", "KGS" },
            { "KHR", "KHR" },
            { "KMF", "KMF" },
            { "KPW", "KPW" },
            { "KRW", "KRW" },
            { "KWD", "KWD" },
            { "KYD", "KYD" },
            { "KZT", "KZT" },
            { "LAK", "LAK" },
            { "LBP", "LBP" },
            { "LKR", "LKR" },
            { "LRD", "LRD" },
            { "LTL", "LTL" },
            { "LVL", "LVL" },
            { "LYD", "LYD" },
            { "MAD", "MAD" },
            { "MDL", "MDL" },
            { "MGA", "MGA" },
            { "MKD", "MKD" },
            { "MMK", "MMK" },
            { "MNT", "MNT" },
            { "MOP", "MOP" },
            { "MRO", "MRO" },
            { "MUR", "MUR" },
            { "MVR", "MVR" },
            { "MWK", "MWK" },
            { "MXN", "MXN" },
            { "MYR", "MYR" },
            { "MZN", "MZN" },
            { "NAD", "NAD" },
            { "NGN", "NGN" },
            { "NIO", "NIO" },
            { "NOK", "NOK" },
            { "NPR", "NPR" },
            { "NZD", "NZD" },
            { "OMR", "OMR" },
            { "PAB", "PAB" },
            { "PEN", "PEN" },
            { "PGK", "PGK" },
            { "PHP", "PHP" },
            { "PKR", "PKR" },
            { "PLN", "PLN" },
            { "PYG", "PYG" },
            { "QAR", "QAR" },
            { "RON", "RON" },
            { "RSD", "RSD" },
            { "RUB", "RUB" },
            { "RWF", "RWF" },
            { "SAR", "SAR" },
            { "SBD", "SBD" },
            { "SCR", "SCR" },
            { "SDG", "SDG" },
            { "SEK", "SEK" },
            { "SGD", "SGD" },
            { "SHP", "SHP" },
            { "SLL", "SLL" },
            { "SOS", "SOS" },
            { "SRD", "SRD" },
            { "SSP", "SSP" },
            { "STD", "STD" },
            { "SYP", "SYP" },
            { "SZL", "SZL" },
            { "THB", "THB" },
            { "TJS", "TJS" },
            { "TMT", "TMT" },
            { "TND", "TND" },
            { "TOP", "TOP" },
            { "TRY", "TRY" },
            { "TTD", "TTD" },
            { "TWD", "TWD" },
            { "TZS", "TZS" },
            { "UAH", "UAH" },
            { "UGX", "UGX" },
            { "USD", "USD" },
            { "UYU", "UYU" },
            { "UZS", "UZS" },
            { "VEF", "VEF" },
            { "VND", "VND" },
            { "VUV", "VUV" },
            { "WST", "WST" },
            { "YER", "YER" },
            { "ZAR", "ZAR" },
            { "ZMW", "ZMW" },
            { "adp", "Andorrskur peseti" },
            { "aed", "Arab\u00edskt d\u00edrham" },
            { "afn", "Afgani" },
            { "all", "Albanskt lek" },
            { "amd", "Armenskt dramm" },
            { "ang", "Hollenskt Antillugyllini" },
            { "aoa", "Ang\u00f3lsk kvansa" },
            { "ara", "Argentine Austral" },
            { "arp", "Argent\u00edskur pesi (1983\u20131985)" },
            { "ars", "Argent\u00ednskur pesi" },
            { "ats", "Austurr\u00edskur skildingur" },
            { "aud", "\u00c1stralskur dalur" },
            { "awg", "Ar\u00fab\u00f6nsk fl\u00f3r\u00edna" },
            { "azn", "Aserskt manat" },
            { "bam", "Skiptanlegt Bosn\u00edu og Herseg\u00f3v\u00ednu-mark" },
            { "bbd", "Barbadoskur dalur" },
            { "bdt", "Bangladessk taka" },
            { "bef", "Belg\u00edskur franki" },
            { "bgl", "Lef" },
            { "bgn", "B\u00falgarskt lef" },
            { "bhd", "Bareinskur denari" },
            { "bif", "B\u00far\u00fand\u00edskur franki" },
            { "bmd", "Berm\u00fadadalur" },
            { "bnd", "Br\u00faneiskur dalur" },
            { "bob", "B\u00f3liv\u00edani" },
            { "bop", "B\u00f3liv\u00edskur pesi" },
            { "bov", "Bolivian Mvdol" },
            { "brl", "Brasil\u00edskt r\u00edal" },
            { "bsd", "Bahamadalur" },
            { "btn", "B\u00fatanskt n\u00faltrum" },
            { "buk", "B\u00farmverskt kjat" },
            { "bwp", "Botsv\u00f6nsk p\u00fala" },
            { "byr", "Hv\u00edtr\u00fassnesk r\u00fabla" },
            { "bzd", "Bel\u00edskur dalur" },
            { "cad", "Kanad\u00edskur dalur" },
            { "cdf", "Kong\u00f3skur franki" },
            { "chf", "Svissneskur franki" },
            { "clf", "Chilean Unidades de Fomento" },
            { "clp", "S\u00edleskur pesi" },
            { "cny", "K\u00ednverskt j\u00faan" },
            { "cop", "K\u00f3lumb\u00edskur pesi" },
            { "crc", "Kostar\u00edskt k\u00f3lon" },
            { "csk", "T\u00e9kknesk kr\u00f3na, eldri" },
            { "cuc", "K\u00fabverskur skiptanlegur pesi" },
            { "cup", "K\u00fabverskur pesi" },
            { "cve", "Gr\u00e6nh\u00f6f\u00f0eyskur sk\u00fati" },
            { "cyp", "K\u00fdpverskt pund" },
            { "czk", "T\u00e9kknesk kr\u00f3na" },
            { "ddm", "Austur\u00fe\u00fdskt mark" },
            { "dem", "\u00de\u00fdskt mark" },
            { "djf", "Dj\u00edb\u00fat\u00edskur franki" },
            { "dkk", "D\u00f6nsk kr\u00f3na" },
            { "dop", "D\u00f3min\u00edskur pesi" },
            { "dzd", "Als\u00edrskur denari" },
            { "ecs", "Ecuador Sucre" },
            { "eek", "Eistnesk kr\u00f3na" },
            { "egp", "Egypskt pund" },
            { "ern", "Er\u00edtresk nakfa" },
            { "esp", "Sp\u00e6nskur peseti" },
            { "etb", "E\u00fe\u00ed\u00f3p\u00edskt birr" },
            { "eur", "Evra" },
            { "fim", "Finnskt mark" },
            { "fjd", "F\u00eddjeyskur dalur" },
            { "fkp", "Falklenskt pund" },
            { "frf", "Franskur franki" },
            { "gbp", "Sterlingspund" },
            { "gel", "Georg\u00edskur lari" },
            { "ghs", "Ganverskur sedi" },
            { "gip", "G\u00edbraltarspund" },
            { "gmd", "Gamb\u00edskur dalasi" },
            { "gnf", "G\u00edneufranki" },
            { "grd", "Drakma" },
            { "gtq", "Gvatemalskt kvesal" },
            { "gwe", "Port\u00fagalskur, g\u00edneskur sk\u00fati" },
            { "gyd", "Gv\u00e6janskur dalur" },
            { "hkd", "Hong Kong-dalur" },
            { "hnl", "Hond\u00farsk lemp\u00edra" },
            { "hrk", "Kr\u00f3at\u00edsk k\u00fana" },
            { "htg", "Ha\u00edt\u00edskur g\u00fardi" },
            { "huf", "Ungversk f\u00f3rinta" },
            { "idr", "Ind\u00f3nes\u00edsk r\u00fap\u00eda" },
            { "iep", "\u00cdrskt pund" },
            { "ilp", "\u00cdsraelskt pund" },
            { "ils", "N\u00fdr \u00edsraelskur sikill" },
            { "inr", "Indversk r\u00fap\u00eda" },
            { "iqd", "\u00cdrakskur denari" },
            { "irr", "\u00cdranskt r\u00edal" },
            { "isk", "\u00cdslensk kr\u00f3na" },
            { "itl", "\u00cdt\u00f6lsk l\u00edra" },
            { "jmd", "Jama\u00edskur dalur" },
            { "jod", "J\u00f3rdanskur denari" },
            { "jpy", "Japanskt jen" },
            { "kes", "Ken\u00edskur skildingur" },
            { "kgs", "Kirgiskt som" },
            { "khr", "Kamb\u00f3d\u00edskt r\u00edal" },
            { "kmf", "K\u00f3moreyskur franki" },
            { "kpw", "Nor\u00f0urk\u00f3reskt vonn" },
            { "krw", "Su\u00f0urk\u00f3reskt vonn" },
            { "kwd", "K\u00faveiskur denari" },
            { "kyd", "Caymaneyskur dalur" },
            { "kzt", "Kasakst tengi" },
            { "lak", "Laoskt kip" },
            { "lbp", "L\u00edbanskt pund" },
            { "lkr", "Sr\u00edl\u00f6nsk r\u00fap\u00eda" },
            { "lrd", "L\u00edber\u00edskur dalur" },
            { "lsl", "Lesotho Loti" },
            { "ltl", "Lith\u00e1\u00edskt l\u00edt" },
            { "ltt", "Lithuanian Talonas" },
            { "luf", "L\u00faxemborgarfranki" },
            { "lvl", "Lettneskt lat" },
            { "lvr", "Lettnesk r\u00fabla" },
            { "lyd", "L\u00edb\u00edskur denari" },
            { "mad", "Marokk\u00f3skt d\u00edrham" },
            { "maf", "Marokk\u00f3skur franki" },
            { "mdl", "Moldav\u00edskt lei" },
            { "mga", "Madagaskararjari" },
            { "mgf", "Madagaskur franki" },
            { "mkd", "Maked\u00f3nskur denari" },
            { "mlf", "Mal\u00edskur franki" },
            { "mmk", "Mjanmarskt kjat" },
            { "mnt", "Mong\u00f3lskur t\u00far\u00edkur" },
            { "mop", "Maka\u00f3pataka" },
            { "mro", "M\u00e1rit\u00f6nsk \u00fag\u00eda" },
            { "mtl", "Meltnesk l\u00edra" },
            { "mtp", "Maltneskt pund" },
            { "mur", "M\u00e1rit\u00edsk r\u00fap\u00eda" },
            { "mvr", "Mald\u00edveysk r\u00fap\u00eda" },
            { "mwk", "Malav\u00edsk kvaka" },
            { "mxn", "Mex\u00edk\u00f3skur pesi" },
            { "mxp", "Mex\u00edk\u00f3skur silfurpesi (1861\u20131992)" },
            { "mxv", "Mex\u00edk\u00f3skur pesi, UDI" },
            { "myr", "Malas\u00edskt ringit" },
            { "mze", "M\u00f3samb\u00edskur sk\u00fati" },
            { "mzn", "M\u00f3samb\u00edskt metikal" },
            { "nad", "Namib\u00edskur dalur" },
            { "ngn", "N\u00edger\u00edsk n\u00e6ra" },
            { "nio", "N\u00edkar\u00f6gsk kord\u00f3va" },
            { "nlg", "Hollenskt gyllini" },
            { "nok", "Norsk kr\u00f3na" },
            { "npr", "Nep\u00f6lsk r\u00fap\u00eda" },
            { "nzd", "N\u00fdsj\u00e1lenskur dalur" },
            { "omr", "\u00d3manskt r\u00edal" },
            { "pab", "Balb\u00f3i" },
            { "pen", "Per\u00faskt s\u00f3l" },
            { "pgk", "Pap\u00fask k\u00edna" },
            { "php", "Filippseyskur pesi" },
            { "pkr", "Pakist\u00f6nsk r\u00fap\u00eda" },
            { "pln", "P\u00f3lskt slot" },
            { "plz", "Slot" },
            { "pte", "Port\u00fagalskur sk\u00fati" },
            { "pyg", "Paragv\u00e6skt gvaran\u00ed" },
            { "qar", "Katarskt r\u00edal" },
            { "rol", "R\u00famenskt lei (1952\u20132006)" },
            { "ron", "R\u00famenskt lei" },
            { "rsd", "Serbneskur denari" },
            { "rub", "R\u00fassnesk r\u00fabla" },
            { "rur", "R\u00fassnesk r\u00fabla (1991\u20131998)" },
            { "rwf", "R\u00faandskur franki" },
            { "sar", "S\u00e1diarab\u00edskt r\u00edal" },
            { "sbd", "Sal\u00f3monseyskur dalur" },
            { "scr", "Seychellesr\u00fap\u00eda" },
            { "sdd", "S\u00fadanskur denari" },
            { "sdg", "S\u00fadanskt pund" },
            { "sdp", "S\u00fadanskt pund (1957\u20131998)" },
            { "sek", "S\u00e6nsk kr\u00f3na" },
            { "sgd", "Singap\u00farskur dalur" },
            { "shp", "Helenskt pund" },
            { "sit", "Sl\u00f3venskur dalur" },
            { "skk", "Sl\u00f3vak\u00edsk kr\u00f3na" },
            { "sll", "S\u00ederrale\u00f3nsk lj\u00f3na" },
            { "sos", "S\u00f3mal\u00edskur skildingur" },
            { "srd", "S\u00far\u00ednamdalur" },
            { "srg", "Suriname Guilder" },
            { "ssp", "Su\u00f0urs\u00fadanskt pund" },
            { "std", "Sa\u00f3 T\u00f3me og Prins\u00edpe-d\u00f3bra" },
            { "sur", "Soviet Rouble" },
            { "svc", "El Salvador Colon" },
            { "syp", "S\u00fdrlenskt pund" },
            { "szl", "Svas\u00edlenskur l\u00edlangeni" },
            { "thb", "Ta\u00edlenskt bat" },
            { "tjr", "Tadsjiksk r\u00fabla" },
            { "tjs", "Tadsjikskur s\u00f3m\u00f3ni" },
            { "tmm", "T\u00farkmenskt manat (1993\u20132009)" },
            { "tmt", "T\u00farkmenskt manat" },
            { "tnd", "T\u00faniskur denari" },
            { "top", "Tongapanga" },
            { "tpe", "T\u00edmorskur sk\u00fati" },
            { "trl", "Tyrknesk l\u00edra (1922\u20132005)" },
            { "try", "Tyrknesk l\u00edra" },
            { "ttd", "Tr\u00ednidad og T\u00f3bag\u00f3-dalur" },
            { "twd", "Ta\u00edvanskur dalur" },
            { "tzs", "Tansan\u00edskur skildingur" },
            { "uah", "\u00dakra\u00ednsk hrinja" },
            { "uak", "Ukrainian Karbovanetz" },
            { "ugx", "\u00dagandskur skildingur" },
            { "usd", "Bandar\u00edkjadalur" },
            { "usn", "Bandar\u00edkjadalur (n\u00e6sta dag)" },
            { "uss", "Bandar\u00edkjadalur (sama dag)" },
            { "uyu", "\u00dar\u00fagv\u00e6skur pesi" },
            { "uzs", "\u00dasbekskt s\u00fam" },
            { "veb", "Bol\u00edvar \u00ed Venes\u00faela (1871\u20132008)" },
            { "vef", "Venes\u00faelskur b\u00f3l\u00edvari" },
            { "vnd", "V\u00edetnamskt dong" },
            { "vuv", "Van\u00faat\u00faskt vat\u00fa" },
            { "wst", "Sam\u00f3atala" },
            { "xaf", "Mi\u00f0afr\u00edskur franki" },
            { "xcd", "Austurkarab\u00edskur dalur" },
            { "xdr", "S\u00e9rst\u00f6k dr\u00e1ttarr\u00e9ttindi" },
            { "xfo", "Franskur gullfranki" },
            { "xfu", "Franskur franki, UIC" },
            { "xof", "Vesturafr\u00edskur franki" },
            { "xpf", "P\u00f3lines\u00edskur franki" },
            { "xxx", "\u00d3\u00feekktur gjaldmi\u00f0ill" },
            { "ydd", "Jemenskur denari" },
            { "yer", "Jemenskt r\u00edal" },
            { "yum", "J\u00fag\u00f3slavneskur denari" },
            { "zal", "Rand (vi\u00f0skipta)" },
            { "zar", "Su\u00f0urafr\u00edskt rand" },
            { "zmk", "Zambian Kwacha (1968\u20132012)" },
            { "zmw", "Samb\u00edsk kvaka" },
            { "zwd", "Simbabveskur dalur" },
        };
        return data;
    }
}
