package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /builddir/build/BUILD/java-1.8.0-openjdk-1.8.0.91-1.b14.el6.x86_64/openjdk/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, May 11, 2016 9:56:39 AM UTC
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
     */
  public static final short value = (short)(4);
}
